### PR TITLE
Add cargo fmt

### LINKED ISSUE #27: Add cargo fmt
Add cargo formatting check to CI

### PR DESCRIPTION
**Pull request by milesgranger**
Will close #27

### CODE REVIEW

**Comment by DarkDrek** [comment]
Can you add a "rustfmt.toml" (even empty?) to enforce a specific formatting?

**Comment by DarkDrek** [comment]
The check step seems to be stuck...? The test on circleci has already finished some time ago! :unamused:

**Comment by DarkDrek** [comment]
Do we want to approve each others PR's? Can you approve your own PR's?

**Comment by milesgranger** [comment]
I'd definitely like to review each other's PRs. Nice having the second pair of eyes. 👍

**Pull request merged**
